server:
  port: 8088

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    queues: helloObj

    # 消息确认机制 --- 是否开启手ack动确认模式
    # [none:不确认 auto:自动确认 manual:手动确认]
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual


